// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID           int64       `json:"id"`
	UserID       pgtype.Int8 `json:"user_id"`
	AddressLine1 string      `json:"address_line1"`
	AddressLine2 pgtype.Text `json:"address_line2"`
	City         string      `json:"city"`
	State        pgtype.Text `json:"state"`
	PostalCode   string      `json:"postal_code"`
	Country      string      `json:"country"`
	CreatedAt    time.Time   `json:"created_at"`
}

type Category struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	CreatedAt   time.Time   `json:"created_at"`
}

type Order struct {
	ID        int64          `json:"id"`
	UserID    pgtype.Int8    `json:"user_id"`
	Total     pgtype.Numeric `json:"total"`
	Status    pgtype.Text    `json:"status"`
	CreatedAt time.Time      `json:"created_at"`
}

type OrderItem struct {
	ID        int64          `json:"id"`
	OrderID   pgtype.Int8    `json:"order_id"`
	ProductID pgtype.Int8    `json:"product_id"`
	Quantity  int32          `json:"quantity"`
	Price     pgtype.Numeric `json:"price"`
}

type Product struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	CategoryID  pgtype.Int8    `json:"category_id"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Review struct {
	ID        int64       `json:"id"`
	UserID    pgtype.Int8 `json:"user_id"`
	ProductID pgtype.Int8 `json:"product_id"`
	Rating    int32       `json:"rating"`
	Comment   pgtype.Text `json:"comment"`
	CreatedAt time.Time   `json:"created_at"`
}

type User struct {
	ID           int64       `json:"id"`
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	FirstName    pgtype.Text `json:"first_name"`
	LastName     pgtype.Text `json:"last_name"`
	CreatedAt    time.Time   `json:"created_at"`
}
